### ISSUE TITLE
FFT

### ISSUE THREAD

**Issue by vmartinv** [mvpossum/eldiego#1]

**Comment by karupayun** [comment]
http://a2oj.com/Category.jsp?ID=42
https://www.codechef.com/JUNE15/problems/MOREFB
http://codeforces.com/contest/528/problem/D
https://icpc.kattis.com/problems/tiles

**Comment by vmartinv** [comment]
metí la multiplicación trivial después intento meter otros! pero bastante seguro que anda

**Comment by vmartinv** [comment]
meti uno re estricto y con el truquito de dar vuela los polinomios. considero que anda todo perfecto.
